# Generated by Django 2.0 on 2017-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20171227_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
