# Generated by Django 2.0 on 2017-12-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20171227_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
