# Generated by Django 2.0 on 2017-12-29 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20171228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='presidents',
            field=models.ManyToManyField(related_name='_club_presidents_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='weeklyMeeting',
            field=models.TimeField(blank=True, verbose_name='Weekly Meeting'),
        ),
    ]
