# Generated by Django 2.0 on 2017-12-29 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20171228_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='weeklyMeeting',
        ),
        migrations.AddField(
            model_name='club',
            name='weeklyMeetingDay',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('Tu', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2),
        ),
        migrations.AddField(
            model_name='club',
            name='weeklyMeetingTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now, verbose_name='Weekly Meeting Time'),
        ),
        migrations.AlterField(
            model_name='club',
            name='creationDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date created'),
        ),
    ]
