# Generated by Django 2.0 on 2017-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20171229_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
