# Generated by Django 2.0 on 2017-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20171230_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.ImageField(blank=True, default="{%static 'clubs/clubdefault.png' %}", upload_to='icons/'),
        ),
    ]
