# Generated by Django 2.0 on 2017-12-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20171230_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.ImageField(blank=True, default="{%static 'clubs/clubdefault.png'%}", upload_to='icons/'),
        ),
    ]
