# Generated by Django 2.0 on 2017-12-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20171230_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('datemade', models.DateField(auto_now_add=True)),
                ('dateevent', models.DateField(blank=True)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='weeklyMeetingPlace',
            field=models.CharField(blank=True, default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='announcements',
            field=models.ManyToManyField(blank=True, related_name='_club_announcements_+', to='clubs.Announcement'),
        ),
    ]
